# Generated by Django 2.1.4 on 2019-01-27 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='best_answer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_answer', to='qaapp.Answer'),
        ),
    ]
